ci: disable html coverage data output
It seems like grcov starting sporadically failing more often when both
html and lcov outputs were enabled. Revert to only generating lcov data
to see if it stops erroring out with errors like the following:

warning: /tmp/.tmpKxzW7Y/pkgcraft-41761-4482928967540068873_3_1.profraw: invalid instrumentation profile data (file header is corrupt)
error: no profile can be merged
Error: 7 [ERROR] Error while executing llvm tools: Failure while running "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata" "merge" "-f" "-" "-sparse" "-o" "/tmp/.tmpKxzW7Y/0/grcov.profdata"

Unfortunately, when it does fail like the above it doesn't return an
error status on command exit so the CI pipeline doesn't error out.