cargo: bump MSRV to 1.79 to avoid build script issues with 1.77
It appears the version checking for build script prefix compat has
issues since errors similar to the following are output when building
with 1.77:

error: the `cargo::` syntax for build script output instructions was
added in Rust 1.77.0, but the minimum supported Rust version of
`arcanist v0.0.5 (/home/runner/work/pkgcraft/pkgcraft/crates/arcanist)`
is 1.77.